Imports

In [1]:
import pandas as pd

Configuration

In [2]:
df = pd.read_csv("aso_inhibitions_with_canonical_gene.csv")
col1 = "target_gene"
col2 = "Canonical Gene Name"

Check unfound canonical genes

In [3]:
not_found = df[df[col2].isna()]

print(f"{len(not_found)} RNA contexts were not found in the genome")

not_found.to_csv("rna_contexts_not_found.csv", index=False)

0 RNA contexts were not found in the genome

Find targets with multiple possible genes

In [4]:
multi_gene_mask = (
    df["Canonical Gene Name"]
    .notna()
    & df["Canonical Gene Name"].str.contains(";", regex=False)
)

count_multi = multi_gene_mask.sum()

print(f"{count_multi} rows have more than one canonical gene")

785 rows have more than one canonical gene

In [9]:
df[multi_gene_mask]

,aso_sequence_5_to_3,inhibition_percent,chemistry,custom_id,target_mrna,target_gene,cell_line,cell_line_species,dosage,cells_per_well,transfection_method,steric_blocking,rna_context,sugar_mods,backbone_mods,Canonical Gene Name
15286,TCGTCCCCGGGCTTCCGCGG,31.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,100.0,6000.0,Lipofection,False,AUGGCCCUCCCGACACCCUCGGACAGCACCCUCCCCGCGGAAGCCC...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
15287,AAACGAGTCTCCGTCGCCGT,48.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,100.0,6000.0,Lipofection,False,AUGGCCCUCCCGACACCCUCGGACAGCACCCUCCCCGCGGAAGCCC...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
15288,AGCAGGCTCGCAGGGCCTCG,0.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,100.0,6000.0,Lipofection,False,AUGGCCCUCCCGACACCCUCGGACAGCACCCUCCCCGCGGAAGCCC...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
15289,GTGGCGATGCCCGGGTACGG,33.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,100.0,6000.0,Lipofection,False,CAGCACCCUCCCCGCGGAAGCCCGGGGACGAGGACGGCGACGGAGA...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
15290,GGCCTGGGCCAGCCGTTCTC,52.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,100.0,6000.0,Lipofection,False,CGGGGACGAGGACGGCGACGGAGACUCGUUUGGACCCCGAGCCAAA...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137094,TGAATCCTGGACTCCG,92.0,length=16 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,200.0,10000.0,Lipofection,False,GUCACCGGAUCCCAGACCGCCCUGCUCCUCCGAGCCUUUGAGAAGG...,"['CET', 'CET', 'CET', 'DNA', 'DNA', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
137095,CAGATCTGAATCCTGG,82.0,length=16 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,200.0,10000.0,Lipofection,False,GGAUCCCAGACCGCCCUGCUCCUCCGAGCCUUUGAGAAGGAUCGCU...,"['CET', 'CET', 'CET', 'DNA', 'DNA', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
137096,CCAGATCTGAATCCTG,90.0,length=16 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,200.0,10000.0,Lipofection,False,GAUCCCAGACCGCCCUGCUCCUCCGAGCCUUUGAGAAGGAUCGCUU...,"['CET', 'CET', 'CET', 'DNA', 'DNA', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
137097,TCGATTCTGAAACCAG,93.0,length=16 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2024...,DUX4,DUX4,54-2,human,200.0,10000.0,Lipofection,False,CCCUGCUCCUCCGAGCCUUUGAGAAGGAUCGCUUUCCAGGCAUCGC...,"['CET', 'CET', 'CET', 'DNA', 'DNA', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
141396,GGTTCAAGCGATTCTCCTGC,46.0,length=20 modifications=[Modification(modifica...,patent-scrape-v2/data/inhibition_tables/US2004...,IAP-like,NAIP,A549,human,NaN,NaN,Other,False,GCCUGGCCAAUAUGGUGAAACUCUGUCUCUACUAAAAAUACAAAGA...,"['MOE', 'MOE', 'MOE', 'MOE', 'MOE', 'DNA', 'DN...","['PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS', 'PS...",NAIPP3;NAIPP1;NAIPP2;NAIPP4;NAIP

In [10]:

fixed_df = df.copy()

multi_gene_mask = (
        fixed_df[col2].notna()
        & fixed_df[col2].str.contains(";", regex=False)
)

print(f"Fixing {multi_gene_mask.sum()} rows with multiple canonical genes")

# Replace Canonical Gene Name with target_gene where ambiguous
fixed_df.loc[multi_gene_mask, col2] = fixed_df.loc[multi_gene_mask, col1]

# Save fixed version
fixed_df.to_csv(
    "aso_inhibitions_with_canonical_gene_fixed.csv",
    index=False
)

print("Saved aso_inhibitions_with_canonical_gene_fixed.csv")

Fixing 785 rows with multiple canonical genes
Saved aso_inhibitions_with_canonical_gene_fixed.csv

function that checks for mismatches between targets and canonical gene names

In [5]:
def check_baddies(df, col_1, col_2):
    baddies = df[df[col_1] != df[col_2]][col_1].unique()
    canonical = df[df[col_1] != df[col_2]][col_2].unique()
    new_df = pd.DataFrame()
    new_df["baddies"] = baddies
    new_df["canonical"] = canonical
    return new_df

execution

In [6]:
new = check_baddies(df, col1, col2)
new.to_csv("canonical_baddies.csv", index=False)

In [7]:
new

   baddies                                          canonical
0      CFB                                         AL645922.1
1     DUX4  DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
2     PAK1                                         AP003680.1
3   NOTCH2               NOTCH2NLC;NOTCH2;NOTCH2NLA;NOTCH2NLB
4    DUSP6                                         AC024909.1
5  PPP2R1A                                            MIR6801
6  EIF2AK2                                          ARL14EPP1
7     NAIP                   NAIPP3;NAIPP1;NAIPP2;NAIPP4;NAIP
8     IGF2                                            IGF2-AS

find cell line for baddies