In [1]:
import pandas as pd
from tauso.data.consts import CANONICAL_GENE
from notebooks.data.OligoAI.assign_canonical_gene import process_and_assign_genes

In [2]:
# Cell 2: Run the pipeline
df, ambiguous_genes = process_and_assign_genes()

Resolving 293 unique target genes
[50/293] genes processed
[100/293] genes processed
[150/293] genes processed
[200/293] genes processed
[250/293] genes processed
[293/293] genes processed
Saved annotated dataframe → /home/michael/career/tauso_article/tauso_source2/notebooks/data/OligoAI/raw_data/aso_inhibitions_with_canonical_gene.csv.gz

/home/michael/career/tauso_article/tauso_source2/notebooks/data/OligoAI/assign_canonical_gene.py:47: UserWarning: 3 target genes mapped to multiple canonical genes
  warnings.warn(f"{len(ambiguous_genes)} target genes mapped to multiple canonical genes")

In [3]:
# Cell 3: Analyze Ambiguous Genes
amb_df = pd.DataFrame(
    [
        {"target_gene": tg, "matched_canonical_genes": ";".join(genes)}
        for tg, genes in ambiguous_genes.items()
    ]
)
display(amb_df)

  target_gene                            matched_canonical_genes
0        DUX4  DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...
1        NAIP                   NAIPP3;NAIPP1;NAIPP2;NAIPP4;NAIP
2      NOTCH2                     NOTCH2NLC;NOTCH2;NBPF10;NBPF14

In [4]:
# Cell 4: Check what happened with the errors
not_found = df[df[CANONICAL_GENE].isna()]
print(f"{len(not_found)} RNA contexts were not found in the genome")

0 RNA contexts were not found in the genome

In [5]:
# Cell 5: Check multi-gene masks
multi_gene_mask = (
    df[CANONICAL_GENE].notna()
    & df[CANONICAL_GENE].str.contains(";", regex=False)
)
count_multi = multi_gene_mask.sum()
print(f"{count_multi} rows have more than one canonical gene")

785 rows have more than one canonical gene

In [6]:
# Cell 6: View multi-gene inconsistencies
display(df[df[CANONICAL_GENE] != df['target_gene']][[CANONICAL_GENE, 'target_gene']].drop_duplicates())

                                      Canonical Gene Name target_gene
15286   DUX4L8;DUX4;DUX4L2;DUX4L3;DUX4L6;DUX4L1;DUX4L5...        DUX4
24132                                       RP11-739B23.1        PAK1
47040                      NOTCH2NLC;NOTCH2;NBPF10;NBPF14      NOTCH2
67898                                               DNMT1       S1PR2
77552                                        RP11-823E8.3       DUSP6
124513                                            MIR6801     PPP2R1A
129677                                          ARL14EPP1     EIF2AK2
141396                   NAIPP3;NAIPP1;NAIPP2;NAIPP4;NAIP        NAIP
150782                                            IGF2-AS        IGF2